/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Utils.IconHelper;
import Utils.Session;

/**
 *
 * @author nitro5
 */
public class Formlogin extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formlogin.class.getName());

  private void setPlacehoder() {
    Username.setText("Username");
    Username.setForeground(java.awt.Color.GRAY);

    Username.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent e) {
        if (Username.getText().equals("Username")) {
          Username.setText("");
          Username.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent e) {
        if (Username.getText().isEmpty()) {
          Username.setText("Username");
          Username.setForeground(java.awt.Color.GRAY);
        }
      }
    });

    Password.setText("Password");
    Password.setForeground(java.awt.Color.GRAY);

    Password.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent e) {
        if (String.valueOf(Password.getPassword()).equals("Password")) {
          Password.setText("");
          Password.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent e) {
        if (String.valueOf(Password.getPassword()).isEmpty()) {
          Password.setText("");
          Password.setEchoChar('*');
          Password.setForeground(java.awt.Color.GRAY);
        }
      }
    });
  }

  private void doLogin() {
    String inputUser = Username.getText().trim();
    String inputPass = String.valueOf(Password.getPassword());

    if (inputUser.isEmpty() || inputUser.equals("Username")) {
      javax.swing.JOptionPane.showMessageDialog(this,
          "Username tidak boleh kosong",
          "Peringatan",
          javax.swing.JOptionPane.WARNING_MESSAGE);
      Username.requestFocus();
      return;
    }

    if (inputPass.isEmpty() || inputPass.equals("Password")) {
      javax.swing.JOptionPane.showMessageDialog(this,
          "Password tidak boleh kosong!",
          "Peringantan",
          javax.swing.JOptionPane.WARNING_MESSAGE);
      Password.requestFocus();
      return;
    }

    try {
      java.sql.Connection c = Database.Koneksi.getKoneksi();
      String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
      java.sql.PreparedStatement p = c.prepareStatement(sql);
      p.setString(1, inputUser);
      p.setString(2, inputPass);
      java.sql.ResultSet r = p.executeQuery();

      if (r.next()) {
        int userId = r.getInt("id");
        String role = r.getString("role");
        String namaLengkap = r.getString("nama_lengkap");
        Session.setUser(userId, namaLengkap, role);

        // Tampilkan popup greeting
        UI.PopUpLogin popupLogin = new UI.PopUpLogin(role);
        popupLogin.setVisible(true);

        this.dispose();
      } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Username atau Password salah!",
            "Login gagal",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        Password.setText("Password");
        Password.setForeground(java.awt.Color.GRAY);
      }
      r.close();
      p.close();
    } catch (Exception e) {
      javax.swing.JOptionPane.showMessageDialog(this,
          "Koneksi database gagal\n" + e.getMessage(),
          "Error",
          javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }

  public Formlogin() {
    initComponents();

    LogoIcon.setIcon(IconHelper.getIcon("/Asset/logo.png", 64, 64));

    setPlacehoder();

    Username.addActionListener(e -> Password.requestFocus());
    Password.addActionListener(e -> doLogin());

    btnLogin.addActionListener(e -> doLogin());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    LogoIcon = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    Username = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    btnLogin = new javax.swing.JButton();
    Password = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));

    LogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/logo.png"))); // NOI18N

    jLabel3.setBackground(new java.awt.Color(238, 238, 238));
    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setText("Selamat Datang di Sistem POS Coffee Amera");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(245, 242, 235));
    jLabel2.setText("Sistem ini dibangun untuk Mempermudah Proses Transaksi ");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(245, 242, 235));
    jLabel4.setText("dan Manajemen Produk");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(LogoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel4)))
                .addContainerGap(28, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(LogoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jPanel2.setBackground(new java.awt.Color(245, 242, 235));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel1.setText("LOGIN");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel5.setText("Username");

    Username.setText("Username");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel6.setText("Password");

    btnLogin.setBackground(new java.awt.Color(51, 51, 51));
    btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnLogin.setForeground(new java.awt.Color(238, 238, 238));
    btnLogin.setText("Login");

    Password.setText("jPasswordField1");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(Password))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190)))));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    setSize(new java.awt.Dimension(1076, 624));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Formlogin().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel LogoIcon;
  private javax.swing.JPasswordField Password;
  private javax.swing.JTextField Username;
  private javax.swing.JButton btnLogin;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
